from __future__ import annotations

import re

from .models import Rule

SUPPORTED_EXTENSIONS = {
    ".py",
    ".js",
    ".jsx",
    ".ts",
    ".tsx",
    ".java",
    ".go",
    ".json",
    ".yaml",
    ".yml",
    ".toml",
    ".ini",
    ".cfg",
    ".conf",
    ".env",
    ".properties",
    ".sh",
    ".pem",
    ".crt",
    ".cer",
    ".key",
    ".pub",
    ".tf",
}

RULES: list[Rule] = [
    Rule(
        id="PQC001",
        title="RSA usage detected",
        description="RSA can indicate public-key cryptography that should be inventoried for post-quantum migration review.",
        pattern=r"\bRSA\b|rsaEncryption|ssh-rsa",
        severity="critical",
        category="public-key-crypto",
        recommendation="Inventory this usage, identify its function (encryption, signature, key exchange), and plan a migration path toward approved or future-approved post-quantum alternatives where applicable.",
        applies_to=("*",),
        flags=re.IGNORECASE,
    ),
    Rule(
        id="PQC002",
        title="Elliptic-curve crypto detected",
        description="ECC/ECDSA/ECDH references likely indicate public-key cryptography that needs migration visibility.",
        pattern=r"\bECC\b|\bECDSA\b|\bECDH\b|secp256r1|prime256v1|ed25519|ed448",
        severity="critical",
        category="public-key-crypto",
        recommendation="Add this location to the crypto inventory and determine whether it is used for signatures, key establishment, certificates, or SSH identities.",
        applies_to=("*",),
        flags=re.IGNORECASE,
    ),
    Rule(
        id="PQC003",
        title="Diffie-Hellman or DSA detected",
        description="DH/DSA references may indicate legacy or review-worthy public-key material.",
        pattern=r"\bDiffieHellman\b|\bDH\b|\bDSA\b|ssh-dss",
        severity="high",
        category="public-key-crypto",
        recommendation="Review whether this is active crypto usage, legacy compatibility, or dead code. Prioritize externally exposed systems first.",
        applies_to=("*",),
        flags=re.IGNORECASE,
    ),
    Rule(
        id="PQC004",
        title="Private key material marker detected",
        description="Private key markers indicate high-sensitivity cryptographic assets that should be inventoried and protected.",
        pattern=r"-----BEGIN (RSA |EC |OPENSSH |PRIVATE )?PRIVATE KEY-----",
        severity="high",
        category="key-material",
        recommendation="Remove secrets from source repositories where possible, rotate if exposed, and record this asset in the cryptographic inventory.",
        applies_to=("*",),
        flags=re.IGNORECASE,
    ),
    Rule(
        id="PQC005",
        title="Certificate or public key material marker detected",
        description="Certificates and public keys are important for migration planning because they often anchor identity and trust flows.",
        pattern=r"-----BEGIN CERTIFICATE-----|-----BEGIN PUBLIC KEY-----",
        severity="high",
        category="certificate-material",
        recommendation="Record the certificate or key, map it to the owning system, and determine the key algorithm and renewal path.",
        applies_to=("*",),
        flags=re.IGNORECASE,
    ),
    Rule(
        id="PQC006",
        title="TLS version appears outdated",
        description="Older TLS versions may reflect technical debt in security-sensitive infrastructure.",
        pattern=r"TLSv1\b|TLSv1\.0|TLSv1\.1|ssl_protocols\s+TLSv1\s+TLSv1\.1",
        severity="high",
        category="transport-security",
        recommendation="Review the service configuration, upgrade protocol settings, and map the endpoint into your migration priority list.",
        applies_to=(".conf", ".cfg", ".ini", ".yaml", ".yml", ".properties", ".json", ".tf"),
        flags=re.IGNORECASE,
    ),
    Rule(
        id="PQC007",
        title="SSH algorithm configuration detected",
        description="SSH crypto configuration can contain algorithms that should be inventoried during post-quantum readiness work.",
        pattern=r"HostKeyAlgorithms|PubkeyAcceptedAlgorithms|KexAlgorithms|ssh-rsa|ecdsa-sha2|curve25519-sha256",
        severity="medium",
        category="ssh-config",
        recommendation="Record the SSH endpoint or config and identify whether algorithm choices are defaults, compatibility settings, or explicit policy.",
        applies_to=(".conf", ".cfg", ".ini", ".sh", ".properties", "*"),
        flags=re.IGNORECASE,
    ),
    Rule(
        id="PQC008",
        title="Common crypto library import detected",
        description="A crypto library import can signal code paths that should be inventoried even before exact algorithms are identified.",
        pattern=r"from\s+cryptography|import\s+cryptography|from\s+Crypto|import\s+Crypto|javax\.crypto|java\.security|node:crypto|require\(['\"]crypto['\"]\)",
        severity="medium",
        category="crypto-library",
        recommendation="Inspect the surrounding code to determine which algorithms are used and whether the library is handling encryption, signatures, certificates, or key generation.",
        applies_to=(".py", ".js", ".jsx", ".ts", ".tsx", ".java", ".go"),
        flags=re.IGNORECASE,
    ),
    Rule(
        id="PQC009",
        title="Hardcoded certificate or key path detected",
        description="Hardcoded certificate or key file references can reveal trust anchors or secret locations important to migration mapping.",
        pattern=r"\.pem\b|\.crt\b|\.cer\b|\.key\b",
        severity="medium",
        category="crypto-asset-reference",
        recommendation="Map the referenced asset to its owning service and identify the key algorithm and replacement process.",
        applies_to=("*",),
        flags=re.IGNORECASE,
    ),
    Rule(
        id="PQC010",
        title="Quantum or post-quantum marker detected",
        description="Mentions of PQC or quantum-safe language may point to migration efforts, experiments, or placeholders.",
        pattern=r"post-quantum|quantum-safe|quantum safe|PQC|ML-KEM|ML-DSA|SLH-DSA",
        severity="low",
        category="migration-context",
        recommendation="Use this finding as contextual inventory information; it may reveal migration planning already underway.",
        applies_to=("*",),
        flags=re.IGNORECASE,
    ),
]
